# Warning! This docker-compose file is for educational use 
# and local testing only. It is very simplified and unsafe.
# Not for production!

version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-pg
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - djangonetwork
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - djangonetwork
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    # command: >
    #   sh -c "python3 manage.py makemigrations &&
    #          python3 manage.py migrate &&
    #          python3 initial_db_fill.py &&
    #          python3 manage.py runserver 0.0.0.0:8000"
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
