FROM postgres:14-alpine

COPY db_dump.sql /docker-entrypoint-initdb.d/
COPY execute_after_db_dump_restore.sh /docker-entrypoint-initdb.d/
RUN chmod 755 /docker-entrypoint-initdb.d/execute_after_db_dump_restore.sh