# Generated by Django 4.0.3 on 2022-03-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_decoration_alter_room_door_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='rooms',
            field=models.ManyToManyField(related_name='beds', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='chair',
            name='rooms',
            field=models.ManyToManyField(related_name='chairs', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='souvenirs',
            field=models.ManyToManyField(related_name='decorations', to='rooms.souvenir'),
        ),
        migrations.AlterField(
            model_name='table',
            name='rooms',
            field=models.ManyToManyField(related_name='tables', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='windowfittings',
            name='windows',
            field=models.ManyToManyField(related_name='fittings', to='rooms.window'),
        ),
    ]
