# Generated by Django 4.0.3 on 2022-04-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomsrelatedobjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsRelatedObjectsMaterializedView',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('door', models.JSONField(blank=True, null=True)),
                ('decoration', models.JSONField(blank=True, null=True)),
                ('windows', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=5, null=True)),
                ('beds', models.JSONField(blank=True, null=True)),
                ('chairs', models.JSONField(blank=True, null=True)),
                ('tables', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rooms_related_objects',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='RoomsRelatedObjects',
        ),
    ]
